apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
      app: telegraf-daemonset
  name: telegraf-daemonset
  namespace: monitoring
spec:
  selector:
    matchLabels:
      name: telegraf-daemonset
  template:
    metadata:
      labels:
        name: telegraf-daemonset
    spec:
      containers:
      - image: telegraf:1.12.3-alpine
        imagePullPolicy: IfNotPresent
        name: telegraf-daemonset
        ports:
        - containerPort: 8125
          protocol: UDP
        volumeMounts:
        - mountPath: /rootfs/sys
          name: sys
          readOnly: true
        - mountPath: /rootfs/proc
          name: proc
          readOnly: true
        - mountPath: /var/run/docker.sock
          name: docker-socket
        - mountPath: /var/run/utmp
          name: utmp
          readOnly: true
        - mountPath: /etc/telegraf
          name: config
        env:
        - name: INFLUX_USER
          valueFrom:
            secretKeyRef:
              name: telegraf-secrets
              key: user
        - name: INFLUX_DB
          valueFrom:
            secretKeyRef:
              name: telegraf-secrets
              key: db
        - name: INFLUX_PW
          valueFrom:
            secretKeyRef:
              name: telegraf-secrets
              key: pw
        - name: INFLUX_URL
          valueFrom:
            secretKeyRef:
              name: telegraf-secrets
              key: url
        - name: CLUSTER_NAME
          valueFrom:
            configMapKeyRef:
              name: telegraf-daemonset
              key: cluster_name
        - name: VER
          value: "1.1"
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: HOST_PROC
          value: /rootfs/proc
        - name: HOST_SYS
          value: /rootfs/sys
        - name: ENV
          value: {{ ENV }}
        resources:
          limits:
            cpu: 300m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
      serviceAccount: telegraf-daemonset
      serviceAccountName: telegraf-daemonset
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /sys
          type: ""
        name: sys
      - hostPath:
          path: /var/run/docker.sock
          type: ""
        name: docker-socket
      - hostPath:
          path: /proc
          type: ""
        name: proc
      - hostPath:
          path: /var/run/utmp
          type: ""
        name: utmp
      - configMap:
          defaultMode: 420
          name: telegraf-daemonset
        name: config
