apiVersion: apps/v1
kind: Deployment
metadata:
  name: statsd
  namespace: sumo-dev
spec:
  selector:
    matchLabels:
      app: statsd
  template:
    metadata:
      labels:
        app: statsd
    spec:
      containers:
        - name: statsd
          image: statsd/statsd:v0.8.5
---
apiVersion: v1
kind: Service
metadata:
  name: statsd-service
  namespace: sumo-dev
  labels:
    kubernetes.io/name: "statsd"
spec:
  selector:
    app: statsd
  ports:
    - name: statsd-tcp
      port: 8125
      protocol: TCP
      targetPort: 8125
    - name: statsd-udp
      port: 8125
      protocol: UDP
      targetPort: 8125
    - name: statsd-admin
      port: 8126
      protocol: TCP
      targetPort: 8126
