apiVersion: ark.heptio.com/v1
kind: Schedule
metadata:
  creationTimestamp: null
  name: cluster-daily
  namespace: heptio-ark
spec:
  schedule: 59 07 * * *
  template:
    excludedNamespaces: null
    excludedResources: null
    hooks:
      resources: null
    includeClusterResources: true
    includedNamespaces:
    - '*'
    includedResources: null
    labelSelector: null
    storageLocation: ""
    ttl: 720h0m0s
    volumeSnapshotLocations: null
status:
  lastBackup: null
  phase: ""
  validationErrors: null

